"""Pure formatters for notification payloads — no network, no side effects, so
they are cheap to unit-test. Digest/anomaly items are plain dicts:
{"metric": str, "period": str, "value": str, "delta": str, "narrative": str}.
"""

from __future__ import annotations

import html


def _row_html(item: dict) -> str:
    return (
        '<tr>'
        f'<td style="padding:8px 10px;font-weight:600">{html.escape(str(item.get("metric","")))}</td>'
        f'<td style="padding:8px 10px;text-align:right">{html.escape(str(item.get("value","")))}</td>'
        f'<td style="padding:8px 10px;text-align:right;color:#2563eb">{html.escape(str(item.get("delta","")))}</td>'
        '</tr>'
    )


def render_digest_email(period: str, items: list[dict]) -> tuple[str, str]:
    """Return (subject, html_body) for a digest email."""
    subject = f"Closebrief digest — {period}"
    rows = "".join(_row_html(it) for it in items) or (
        '<tr><td style="padding:8px 10px" colspan="3">No notable movements.</td></tr>'
    )
    narratives = "".join(
        f'<p style="margin:10px 0;font-size:13px;line-height:1.5;color:#334155">'
        f'<b>{html.escape(str(it.get("metric","")))}:</b> {html.escape(str(it.get("narrative","")))}</p>'
        for it in items
        if it.get("narrative")
    )
    body = f"""\
<div style="font-family:system-ui,Segoe UI,sans-serif;max-width:640px;margin:0 auto;color:#0f172a">
  <h2 style="border-bottom:2px solid #2563eb;padding-bottom:8px">Closebrief · FP&amp;A Digest</h2>
  <p style="color:#64748b;font-size:13px">Period {html.escape(period)}</p>
  <table style="width:100%;border-collapse:collapse;font-size:13px;margin:12px 0">
    <thead><tr style="background:#f6f6f4">
      <th style="padding:8px 10px;text-align:left">Metric</th>
      <th style="padding:8px 10px;text-align:right">Value</th>
      <th style="padding:8px 10px;text-align:right">vs plan</th>
    </tr></thead>
    <tbody>{rows}</tbody>
  </table>
  {narratives}
  <p style="color:#94a3b8;font-size:11px;margin-top:18px">Generated by Closebrief · Confidential</p>
</div>"""
    return subject, body


def render_anomaly_email(anomalies: list[dict]) -> tuple[str, str]:
    subject = f"Closebrief alert — {len(anomalies)} anomaly(ies) detected"
    rows = "".join(_row_html(it) for it in anomalies)
    body = f"""\
<div style="font-family:system-ui,Segoe UI,sans-serif;max-width:640px;margin:0 auto;color:#0f172a">
  <h2 style="border-bottom:2px solid #dc2626;padding-bottom:8px">⚠ Anomaly Alert</h2>
  <table style="width:100%;border-collapse:collapse;font-size:13px;margin:12px 0">
    <tbody>{rows}</tbody>
  </table>
  <p style="color:#94a3b8;font-size:11px;margin-top:18px">Generated by Closebrief · Confidential</p>
</div>"""
    return subject, body


def slack_anomaly_blocks(anomalies: list[dict]) -> dict:
    """Slack Block Kit payload for an anomaly alert."""
    blocks: list[dict] = [
        {"type": "header", "text": {"type": "plain_text", "text": f"⚠ {len(anomalies)} anomaly(ies) detected"}}
    ]
    for a in anomalies:
        line = f"*{a.get('metric','')}* — {a.get('value','')}  ({a.get('delta','')})"
        if a.get("narrative"):
            line += f"\n{a['narrative']}"
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": line}})
    return {"text": f"{len(anomalies)} anomaly(ies) detected", "blocks": blocks}


def slack_digest_blocks(period: str, items: list[dict]) -> dict:
    blocks: list[dict] = [
        {"type": "header", "text": {"type": "plain_text", "text": f"Closebrief digest — {period}"}}
    ]
    for it in items:
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*{it.get('metric','')}*: {it.get('value','')} ({it.get('delta','')})"},
        })
    return {"text": f"Closebrief digest — {period}", "blocks": blocks}


def webhook_payload(event: str, data: dict) -> dict:
    """Canonical outbound webhook JSON body."""
    from datetime import datetime, timezone

    return {
        "event": event,          # anomaly_detected | digest_generated | narrative_failed
        "source": "closebrief",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "data": data,
    }
