-- Closebrief Postgres schema (v1.1). Idempotent — safe to re-run.
-- Mirrors the SQLite schema; is_anomaly stays INTEGER (0/1) so call sites
-- behave identically on both backends.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    category TEXT NOT NULL DEFAULT 'Uncategorized',
    unit TEXT NOT NULL DEFAULT 'USD',
    direction_good TEXT NOT NULL DEFAULT 'up'
);

CREATE TABLE IF NOT EXISTS metric_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_id BIGINT NOT NULL REFERENCES metrics(id),
    period TEXT NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    budget DOUBLE PRECISION,
    quantity DOUBLE PRECISION,
    price DOUBLE PRECISION,
    budget_quantity DOUBLE PRECISION,
    budget_price DOUBLE PRECISION,
    dimensions TEXT,
    UNIQUE(metric_id, period)
);

CREATE TABLE IF NOT EXISTS computed_facts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_id BIGINT NOT NULL REFERENCES metrics(id),
    period TEXT NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    prior_value DOUBLE PRECISION,
    mom_pct DOUBLE PRECISION,
    yoy_pct DOUBLE PRECISION,
    budget_var_abs DOUBLE PRECISION,
    budget_var_pct DOUBLE PRECISION,
    trend TEXT,
    is_anomaly INTEGER NOT NULL DEFAULT 0,
    UNIQUE(metric_id, period)
);

CREATE TABLE IF NOT EXISTS context_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    metric_tags TEXT NOT NULL DEFAULT '',
    effective_date TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- pgvector storage (replaces the FAISS index file). `dim` is recorded so a
-- switched embedding model never compares vectors of different dimensions.
CREATE TABLE IF NOT EXISTS context_vectors (
    context_id BIGINT PRIMARY KEY REFERENCES context_documents(id) ON DELETE CASCADE,
    embedding vector NOT NULL,
    dim INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS generated_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_id BIGINT NOT NULL REFERENCES metrics(id),
    period TEXT NOT NULL,
    narrative TEXT,
    sources TEXT NOT NULL DEFAULT '[]',
    confidence TEXT NOT NULL,
    faithfulness TEXT NOT NULL,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    cost_usd DOUBLE PRECISION,
    latency_ms DOUBLE PRECISION,
    prompt_version TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS uploads (
    id TEXT PRIMARY KEY,
    filename TEXT NOT NULL,
    file_path TEXT NOT NULL,
    sheets TEXT NOT NULL DEFAULT '[]',
    chosen_sheet TEXT,
    profiled_schema TEXT,
    mapping TEXT,
    column_signature TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mapping_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    column_signature TEXT UNIQUE NOT NULL,
    mapping TEXT NOT NULL,
    kpi_config TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS kpi_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_metric TEXT UNIQUE NOT NULL,
    display_name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Uncategorized',
    unit TEXT NOT NULL DEFAULT 'USD',
    direction_good TEXT NOT NULL DEFAULT 'up',
    budget_source TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL REFERENCES generated_reports(id),
    action TEXT NOT NULL,
    edited_text TEXT,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_metric_values_period ON metric_values(period);
CREATE INDEX IF NOT EXISTS idx_computed_facts_period ON computed_facts(period);
CREATE INDEX IF NOT EXISTS idx_reports_metric_period ON generated_reports(metric_id, period);
