-- v1.2: dimension-level P/V/M bridges + LLM call log for /costs.

CREATE TABLE IF NOT EXISTS pvm_bridges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_id BIGINT NOT NULL REFERENCES metrics(id),
    period TEXT NOT NULL,
    volume DOUBLE PRECISION NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    mix DOUBLE PRECISION NOT NULL,
    total DOUBLE PRECISION NOT NULL,
    n_items INTEGER NOT NULL DEFAULT 1,
    UNIQUE(metric_id, period)
);

CREATE TABLE IF NOT EXISTS llm_calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint TEXT NOT NULL,
    model TEXT,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    cost_usd DOUBLE PRECISION,
    latency_ms DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_llm_calls_created ON llm_calls(created_at);
